version: '3'

services:

  oxid6_apache:
    build: 
      context: container/apache/.
      args:
        - PHP_VERSION=${PHP_VERSION}
    hostname: ${DOMAIN}
    container_name: ox6-apache
    restart: unless-stopped
    depends_on:
      - oxid6_mysql
    volumes:
      - ./data/www/:/var/www/html/:cached
    environment:
      DOMAIN: ${DOMAIN}
      APACHE_PORT: ${APACHE_PORT}
      OXID_VERSION: ${OXID_VERSION}
      OXID_DEMODATA: ${OXID_DEMODATA}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${APACHE_PORT}:80
      - ${APACHE_HTTPS_PORT}:443
    links:
      - oxid6_mailhog:mail.server
      
  oxid6_mysql:
    image: mariadb:10.4 # officially tested version by Oxid
    hostname: mysql.${DOMAIN}
    container_name: ox6-db
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  oxid6_mailhog:
    hostname: mailhog.${DOMAIN}
    image: mailhog/mailhog
    container_name: ox6-mailhog
    ports:
      - ${MAILHOG_PORT}:8025

  oxid6_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ox6-pma
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: oxid6_mysql